# Generated by Django 3.0.2 on 2020-02-08 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('ingredient_type', models.CharField(choices=[('NUT', 'Nut'), ('SHELLFISH', 'Shellfish'), ('SEAFOOD', 'Seafood'), ('VEGETABLE', 'Vegetable'), ('BEEF', 'Beef'), ('PORK', 'Pork'), ('CHICKEN', 'Chicken'), ('UNKNOWN', 'Unkown')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('servings', models.IntegerField()),
                ('prep_time', models.IntegerField()),
                ('cuisine', models.CharField(choices=[('CHINESE', 'Chinese'), ('JAPANESE', 'Japanese'), ('KOREAN', 'Korean'), ('VIETNAMESE', 'Vietnamese'), ('THAI', 'Thai'), ('FRENCH', 'French'), ('AMERICAN', 'American'), ('SPANISH', 'Spanish'), ('MEXICAN', 'Mexican'), ('UNKOWN', 'unknown')], max_length=255)),
                ('category', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('APPETIZER', 'Appetizer'), ('UNKOWN', 'Unkown')], max_length=255)),
                ('notes', models.TextField()),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_name', models.CharField(max_length=255)),
                ('video_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('instruction', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe')),
                ('techique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cookbook.Techniques')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cookbook.Ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe')),
            ],
        ),
    ]
