# Generated by Django 3.0.7 on 2020-06-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe_Ingredient',
            new_name='Recipe_Ingredients',
        ),
    ]
