# Generated by Django 3.0.2 on 2020-02-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('NUT', 'Nut'), ('SHELLFISH', 'Shellfish'), ('SEAFOOD', 'Seafood'), ('VEGETABLE', 'Vegetable'), ('BEEF', 'Beef'), ('PORK', 'Pork'), ('CHICKEN', 'Chicken'), ('DAIRY', 'Dairy'), ('STARCH', 'Starch'), ('SEASONING', 'Seasoning'), ('UNKNOWN', 'unknown')], max_length=255),
        ),
    ]
