# Generated by Django 3.0.2 on 2020-02-12 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('NUT', 'Nut'), ('SHELLFISH', 'Shellfish'), ('SEAFOOD', 'Seafood'), ('VEGETABLE', 'Vegetable'), ('BEEF', 'Beef'), ('PORK', 'Pork'), ('CHICKEN', 'Chicken'), ('DAIRY', 'Dairy'), ('UNKNOWN', 'Unkown')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe_step',
            name='techique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cookbook.Technique'),
        ),
    ]
