# Generated by Django 3.0.2 on 2020-02-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20200211_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('NUT', 'Nut'), ('SHELLFISH', 'Shellfish'), ('SEAFOOD', 'Seafood'), ('VEGETABLE', 'Vegetable'), ('BEEF', 'Beef'), ('PORK', 'Pork'), ('CHICKEN', 'Chicken'), ('DAIRY', 'Dairy'), ('STARCH', 'Starch'), ('UNKNOWN', 'unknown')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('APPETIZER', 'Appetizer'), ('UNKNOWN', 'Unknown')], max_length=255),
        ),
    ]
