# Generated by Django 3.0.2 on 2020-02-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20200212_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
    ]
