# Generated by Django 3.0.5 on 2020-06-29 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20200606_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_ingredients',
            name='section_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe_ingredients',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe_instructions',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe'),
        ),
    ]
