# Generated by Django 3.0.2 on 2020-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_author_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='technique',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
