# Generated by Django 3.0.5 on 2020-06-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20200628_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_instructions',
            name='section_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
