# Generated by Django 3.0.2 on 2020-02-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20200211_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='technique_tutorial',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('APPETIZER', 'Appetizer'), ('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('DESSERT', 'Dessert'), ('UNKNOWN', 'Unknown')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='amount',
            field=models.CharField(max_length=144),
        ),
    ]
