# Generated by Django 3.0.2 on 2020-02-13 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20200211_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='technique',
            name='video_link',
            field=models.CharField(max_length=144),
        ),
    ]
