# Generated by Django 3.0.2 on 2020-02-13 00:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_auto_20200212_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 13, 0, 43, 1, 906311, tzinfo=utc), verbose_name='date published'),
        ),
    ]
