# Generated by Django 3.0.5 on 2020-07-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_auto_20200628_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredients',
            name='section_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe_instructions',
            name='section_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
