# Generated by Django 3.0.2 on 2020-02-13 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_auto_20200212_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Published'),
        ),
    ]
